version: '3.8'

services:
  db:
    container_name: stocker-postgres
    image: postgres:15-alpine
    expose:
      - "5432" # Expose port 5432 to the container internally
    volumes:
      - stocker_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"

  backend:
    container_name: stocker-backend
    build: ./backend
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    # volumes:
    #   - ./backend:/app  # Hot Reload: 改 code 即時生效
    ports:
      - "8002:8000"  # 主機 8002 映射到容器 8000
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:
    container_name: stocker-frontend
    build: ./frontend
    environment:
      - VITE_ALLOWED_HOSTS=${ALLOWED_HOSTS}
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules # 避免本地 node_modules 覆蓋容器內的
    ports:
      - "8082:80"
    restart: always

  # === Redis (Optional) ===
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

volumes:
  stocker_db_data: